language: node_js
node_js: node
sudo: false
addons:
  apt:
    packages:
    - jq
env:
  global:
  - SPEC_FILE: https://thebluealliance.com/swagger/api_v3.json
  - USER_NAME: tweirtx
  - GITHUB_ORG: tweirtx
  - secure: m+GSFKEz0z0DczE21L+CN/u1gds9lakSK/DSj8xmEiK+NhBOAMyH1wB/+QDGhv7+Iw085v2pqYJ26Ua/gLAXXK+uC0LjoLAvvJGms8cS9XrxaS8i4Yt85k0wQYDW//PqjMtWapMcJAT7vCpvDaSzY+C5SzbxDmrrlarju7XfMsr82LnPgT36tzk6MT8M9LLsp6Yx/igbi0SpgVwEGWHBzryLrx5MtTVNF2QnkJ9Fjum2SzRlOX1VYTvVavXriyTCyvldKOIj6P/1o0WXRqDe4zTFtkZN/3W5jy/a1+YyMuzNwDfp8cPu3vkp3oD0xJR7jejHhLF0p44/zXs6ZXtsRrZWLYaGkbAmFGaFpRaJ+Uecnj2JA3Gllv2Bmy36RjgZP+qFc8Fjq4+WK4YOoUUHnAv19bzccV8ISFYmMfTiRU9Y/r7xaV9tgLGByQE3WIgakB2VxnvxdutqWSt/aLkkiWh8nuLFMYffpH041BtdbTq/9j5yhUG+wFdeKv6gkMgRwzgMEydFe4HDNJDokvpF2Ne5QkAI3dKroOkjBzjoa97GiiY0Zwnny9o0oIpJFB4royLI70Wni0vHsQ+RIh0POyxCRZcDe4/gSkykbSDgjgXslmDt4uX1QfA/GqsogMfcyvhJ3EIg41XRSz82LPQ3ASLfKoioHYno58a+BIlICLY=
  matrix:
  - OUTLANG=java
  - OUTLANG=kotlin
  - OUTLANG=php
  - OUTLANG=python
  - OUTLANG=javascript
  - OUTLANG=csharp-netcore
  - OUTLANG=swift
  - OUTLANG=ruby
  - OUTLANG=go
  - OUTLANG=dart
install:
- npm install @openapitools/openapi-generator-cli -g
- export APIVERSION=`wget $SPEC_FILE && cat api_v3.json | jq -r '.info.version'`
before_script:
- export REPO_NAME="tba-api-client-$OUTLANG"
- git clone https://$USER_NAME:$GIT_TOKEN@github.com/$GITHUB_ORG/$REPO_NAME.git
script:
- "./codegen.sh"
after_success:
- cd $REPO_NAME
- ../git_push.sh $USER_NAME $REPO_NAME "Updating to API version $APIVERSION" "v$APIVERSION"
- cd ..
after_failure:
- cat test_failures.temp
